spring.application.name=billing-system

spring.datasource.username=root
spring.datasource.password=Adi@758493

spring.datasource.url=jdbc:mysql://localhost:3306/LoginDB?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect